namespace StEn.FinCalcR.Calculations.Calculator.Commands
{
    public enum CommandWord
    {
        None = 0,
        DecimalSeparator = 1,
        GetEffectiveInterest,
        SetEffectiveInterest,
        CalculateEffectiveInterest,
        GetNominalInterestRate,
        SetNominalInterestRate,
        GetStart,
        SetStart,
        CalculateStart,
        SetAdvance,
        GetRate,
        SetRate,
        CalculateRate,
        GetRepaymentRate,
        SetRepaymentRate,
        GetEnd,
        SetEnd,
        CalculateEnd,
        GetRatesPerAnnum,
        SetRatesPerAnnum,
        PercentCalculation,
        Clear,
        Operator,
        Digit,
        AlgebSign,
        Calculate,
        LoadMemoryValue,
        CalculateYears,
        GetYears,
        SetYears,
    }
}
