//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StEn.FinCalcR.Common.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StEn.FinCalcR.Common.LanguageResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über die App.
        /// </summary>
        public static string AboutNavigationItem_Name {
            get {
                return ResourceManager.GetString("AboutNavigationItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinCalcR.
        /// </summary>
        public static string AppTitleTxt_Text {
            get {
                return ResourceManager.GetString("AppTitleTxt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string AppVersionLabelTxt_Text {
            get {
                return ResourceManager.GetString("AppVersionLabelTxt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string CALC_DECIMAL_SEPARATOR {
            get {
                return ResourceManager.GetString("CALC_DECIMAL_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string CALC_THOUSANDS_SEPARATOR {
            get {
                return ResourceManager.GetString("CALC_THOUSANDS_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler!.
        /// </summary>
        public static string DialogErrorTitleLbl_Text {
            get {
                return ResourceManager.GetString("DialogErrorTitleLbl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis!.
        /// </summary>
        public static string DialogHintTitleLbl_Text {
            get {
                return ResourceManager.GetString("DialogHintTitleLbl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DialogOkBtn_Content {
            get {
                return ResourceManager.GetString("DialogOkBtn_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlermeldung:.
        /// </summary>
        public static string ErrorMessageLbl {
            get {
                return ResourceManager.GetString("ErrorMessageLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das folgende Argument ist leer oder null:.
        /// </summary>
        public static string EXC_ARGUMENT_NULL {
            get {
                return ResourceManager.GetString("EXC_ARGUMENT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Applikation muss beendet werden!.
        /// </summary>
        public static string EXC_ERROR_EVENT_GENERAL_APP_NEEDS_SHUTDOWN {
            get {
                return ResourceManager.GetString("EXC_ERROR_EVENT_GENERAL_APP_NEEDS_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler ist aufgetreten!.
        /// </summary>
        public static string EXC_ERROR_EVENT_GENERAL_TITLE {
            get {
                return ResourceManager.GetString("EXC_ERROR_EVENT_GENERAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine unbehandelte Ausnahme ist aufgetreten:.
        /// </summary>
        public static string EXC_GUI_UNHANDLED_EXCEPTION_OCCURED {
            get {
                return ResourceManager.GetString("EXC_GUI_UNHANDLED_EXCEPTION_OCCURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Eingabe ist keine gültige Zahl..
        /// </summary>
        public static string EXC_PARSE_DOUBLE_IMPOSSIBLE {
            get {
                return ResourceManager.GetString("EXC_PARSE_DOUBLE_IMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendung schließen.
        /// </summary>
        public static string ExitAppBtn_ToolTip {
            get {
                return ResourceManager.GetString("ExitAppBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finanztaschenrechner.
        /// </summary>
        public static string FinCalcItem_Name {
            get {
                return ResourceManager.GetString("FinCalcItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innerer Fehler:.
        /// </summary>
        public static string InnerErrorMessageLbl_Text {
            get {
                return ResourceManager.GetString("InnerErrorMessageLbl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail-Kontakt.
        /// </summary>
        public static string MailContactLabel_Text {
            get {
                return ResourceManager.GetString("MailContactLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendung minimieren.
        /// </summary>
        public static string MinAppBtn_ToolTip {
            get {
                return ResourceManager.GetString("MinAppBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt-Homepage.
        /// </summary>
        public static string ProjectHomepageLabelTxt_Text {
            get {
                return ResourceManager.GetString("ProjectHomepageLabelTxt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string SnackBar_Action_Content_Details {
            get {
                return ResourceManager.GetString("SnackBar_Action_Content_Details", resourceCulture);
            }
        }
    }
}
